spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: freelancer-service
          uri: lb://freelancer-service
          predicates:
            - Path=/equipes/**
          filters:
            - StripPrefix=1
